server:
  port: 8092

spring:
  application:
    name: consumer2
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  #management:
  #  endpoints:
  #    web:
  #      exposure:
  #        include: *




